# Numpy two dimensional arrays

In [104]:
import numpy as np

## Common settings

### Dimension tuple

In [105]:
from collections import namedtuple

Rect = namedtuple('Rect', 'height width')
rect_7x5 = Rect(5, 7)
rect_3x2 = Rect(2, 3)

### Fills with zeros

In [106]:
zeros_arr = np.zeros(rect_7x5)
zeros_arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Fills with other (5)

In [107]:
np.full(rect_3x2, 5)

array([[5, 5, 5],
       [5, 5, 5]])

### Incremental range

In [108]:
incr_7x5 = np.arange(7*5).reshape(rect_7x5)
incr_7x5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

### Fibonacci

In [109]:
def fibonacci(n: int):
    range_to_n = np.arange(1, n + 1)
    length_range = len(range_to_n)
    
    # Binet Formula
    sqrtFive = np.sqrt(5) 
    alpha = (1 + sqrtFive) / 2
    beta = (1 - sqrtFive) / 2
    return np.rint(((alpha ** range_to_n) - (beta ** range_to_n)) / (sqrtFive))


fibonacci(10)
    

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

## Generate value based on x, y

In [110]:
def gen_for_y0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_y0(zeros_arr, rect_7x5)    

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [111]:
def gen_for_x0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_x0(zeros_arr, rect_7x5)    

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [112]:
def gen_for_ymax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == dimension[0]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_ymax(zeros_arr, rect_7x5) 

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])

In [113]:
def gen_for_xmax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == dimension[1]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_xmax(zeros_arr, rect_7x5)    

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [114]:
def for_xy(x, y, dimension):
    return x + y

def gen_for_xy(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy(it.multi_index[1], it.multi_index[0], dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy(zeros_arr, rect_7x5)    

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [115]:
def for_xy_previous(x, y, previous, dimension):
    return x + y + previous

def gen_for_xy_previous(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_previous(it.multi_index[1], it.multi_index[0], v,  dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy_previous(gen_for_y0(zeros_arr, rect_7x5), rect_7x5)    

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [116]:
def for_xy_3x3_local(x, y, threeByThree, dimension):
    #Adds West + North
    return threeByThree[0, -1] + threeByThree[1, 0]
    
def for_xy_3x3_strict(x, y, arr, dimension):
    if y == 0 or y >= dimension[0]-1 or x == 0 or x >= dimension[1]-1:
        # keep old value
        return arr[y, x]
    else:
        return for_xy_3x3_local(x, y, arr[y-1:y+1, x-1:x+1], dimension)

def gen_for_xy_3x3_strict(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_3x3_strict(it.multi_index[1], it.multi_index[0], arr,  dimension)for v in it]).reshape(dimension)
    return new_arr

print(incr_7x5)
gen_for_xy_3x3_strict(incr_7x5, rect_7x5)  

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8, 10, 12, 14, 16, 13],
       [14, 22, 24, 26, 28, 30, 20],
       [21, 36, 38, 40, 42, 44, 27],
       [28, 29, 30, 31, 32, 33, 34]])