# Numpy two dimensional arrays

In [51]:
import numpy as np

## Common settings

### Dimension tuple

In [52]:
from collections import namedtuple

Rect = namedtuple('Rect', 'height width')
rect_7x5 = Rect(5, 7)
rect_3x2 = Rect(2, 3)

### Fills with zeros

In [53]:
zeros_arr = np.zeros(rect_7x5)
zeros_arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Fills with other (5)

In [54]:
np.full(rect_3x2, 5)

array([[5, 5, 5],
       [5, 5, 5]])

## Generate value based on x, y

In [55]:
def gen_for_y0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_y0(zeros_arr, rect_7x5)    

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [56]:
def gen_for_x0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_x0(zeros_arr, rect_7x5)    

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [57]:
def gen_for_ymax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == dimension[0]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_ymax(zeros_arr, rect_7x5) 

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])

In [58]:
def gen_for_xmax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == dimension[1]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_xmax(zeros_arr, rect_7x5)    

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [59]:
def for_xy(x, y, dimension):
    return x + y

def gen_for_xy(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy(it.multi_index[1], it.multi_index[0], dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy(zeros_arr, rect_7x5)    

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [60]:
def for_xy_previous(x, y, previous, dimension):
    return x + y + previous

def gen_for_xy_previous(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_previous(it.multi_index[1], it.multi_index[0], v,  dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy_previous(gen_for_y0(zeros_arr, rect_7x5), rect_7x5)    

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [61]:
def for_xy_3x3_local(x, y, threeByThree, dimension):
    return threeByThree[0, -1] + threeByThree[1, 0]
    
def for_xy_3x3_strict(x, y, arr, dimension):
    if y == 0 or y >= dimension[0]-1 or x == 0 or x >= dimension[1]-1:
        return 0
    else:
        return arr[x, y]
#         return for_xy_3x3_local(x, y, arr[y-1:y+1, x-1:x+1], dimension)

def gen_for_xy_3x3_strict(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_3x3_strict(it.multi_index[1], it.multi_index[0], arr,  dimension)for v in it]).reshape(dimension)
    return new_arr

# gen_for_xy_3x3_strict(gen_for_y0(zeros_arr, rect_7x5), rect_7x5)  