# Numpy two dimensional arrays

In [295]:
import numpy as np

## Common settings

### Dimension tuple

In [296]:
from collections import namedtuple

Rect = namedtuple('Rect', 'height width')
rect_7x5 = Rect(5, 7)
rect_3x2 = Rect(2, 3)

### Fills with zeros

In [297]:
zeros_arr = np.zeros(rect_7x5)
zeros_arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Fills with other (5)

In [298]:
np.full(rect_3x2, 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [299]:
ones_arr = np.ones(rect_7x5)
two_arr = np.full(rect_7x5, 2)
three_arr = np.full(rect_7x5, 3)
four_arr = np.full(rect_7x5, 4)
five_arr = np.full(rect_7x5, 5)

### Incremental range

In [300]:
incr_7x5 = np.arange(7*5).reshape(rect_7x5)
incr_7x5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [301]:
decr_7x5 = np.arange(7*5,0, -1).reshape(rect_7x5)
decr_7x5

array([[35, 34, 33, 32, 31, 30, 29],
       [28, 27, 26, 25, 24, 23, 22],
       [21, 20, 19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1]])

In [302]:
incr_7x5_by3 = np.arange(0, 7*5*3, 3).reshape(rect_7x5)
incr_7x5_by3

array([[  0,   3,   6,   9,  12,  15,  18],
       [ 21,  24,  27,  30,  33,  36,  39],
       [ 42,  45,  48,  51,  54,  57,  60],
       [ 63,  66,  69,  72,  75,  78,  81],
       [ 84,  87,  90,  93,  96,  99, 102]])

In [303]:
incr_7x5_by5 = np.arange(0, 7*5*5, 5).reshape(rect_7x5)
incr_7x5_by5

array([[  0,   5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125, 130, 135],
       [140, 145, 150, 155, 160, 165, 170]])

### Fibonacci

 * sqrt: Return the non-negative square-root of an array, element-wise.
 * rint: Round elements of the array to the nearest integer.


In [304]:
def fibonacci(n: int):
    range_to_n = np.arange(1, n + 1)
    length_range = len(range_to_n)
    
    # Binet Formula
    sqrtFive = np.sqrt(5)
    print("sqrtFive", sqrtFive)
    alpha = (1 + sqrtFive) / 2
    beta = (1 - sqrtFive) / 2
    return np.rint(((alpha ** range_to_n) - (beta ** range_to_n)) / (sqrtFive))


fibonacci(10)
    

sqrtFive 2.23606797749979


array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

## Generate value based on x, y

### Populate top row with 1

In [305]:
def gen_for_y0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_y0(zeros_arr, rect_7x5)    

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

### Populate left column with 1

In [306]:
def gen_for_x0(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == 0 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_x0(zeros_arr, rect_7x5)    

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

### Populate bottom row with 1

In [307]:
def gen_for_ymax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[0] == dimension[0]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_ymax(zeros_arr, rect_7x5) 

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])

### Populate right column with 1

In [308]:
def gen_for_xmax(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([1 if it.multi_index[1] == dimension[1]-1 else 0 for v in it]).reshape(dimension)
    return new_arr

gen_for_xmax(zeros_arr, rect_7x5)    

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1]])

### Adds x and y

In [309]:
def for_xy(x, y, dimension):
    return x + y

def gen_for_xy(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy(it.multi_index[1], it.multi_index[0], dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy(zeros_arr, rect_7x5)    

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

### Adds x and y on top of previous value

In [310]:
def for_xy_previous(x, y, previous, dimension):
    return x + y + previous

def gen_for_xy_previous(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_previous(it.multi_index[1], it.multi_index[0], v,  dimension)for v in it]).reshape(dimension)
    return new_arr

gen_for_xy_previous(gen_for_y0(zeros_arr, rect_7x5), rect_7x5)    

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

### Modify value based on immediate neighbour

In [311]:
def for_xy_3x3_local(x, y, threeByThree, dimension):
    #Adds West + North
    return threeByThree[0, -1] + threeByThree[1, 0]
    
def for_xy_3x3_strict(x, y, arr, dimension):
    if y == 0 or y >= dimension[0]-1 or x == 0 or x >= dimension[1]-1:
        # keep old value
        return arr[y, x]
    else:
        return for_xy_3x3_local(x, y, arr[y-1:y+1, x-1:x+1], dimension)

def gen_for_xy_3x3_strict(arr, dimension):
    it = np.nditer(arr, flags=['multi_index'])
    new_arr = np.array([for_xy_3x3_strict(it.multi_index[1], it.multi_index[0], arr,  dimension)for v in it]).reshape(dimension)
    return new_arr

print(incr_7x5)
gen_for_xy_3x3_strict(incr_7x5, rect_7x5)  

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8, 10, 12, 14, 16, 13],
       [14, 22, 24, 26, 28, 30, 20],
       [21, 36, 38, 40, 42, 44, 27],
       [28, 29, 30, 31, 32, 33, 34]])

## Merging 2D arrays

In [312]:
ones_arr+two_arr

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [313]:
two_arr*five_arr

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [314]:
five_arr-two_arr == three_arr

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [315]:
two_arr > ones_arr

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [316]:
(ones_arr+two_arr)*four_arr

array([[12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12.]])

In [317]:
incr_7x5*2

array([[ 0,  2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66, 68]])

In [318]:
incr_7x5/2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5],
       [14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ]])

In [319]:
incr_7x5*incr_7x5

array([[   0,    1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144,  169],
       [ 196,  225,  256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089, 1156]])

## Other

### Transpose

Reverse or permute the axes of an array; returns the modified array.

In [320]:
np.transpose(incr_7x5)

array([[ 0,  7, 14, 21, 28],
       [ 1,  8, 15, 22, 29],
       [ 2,  9, 16, 23, 30],
       [ 3, 10, 17, 24, 31],
       [ 4, 11, 18, 25, 32],
       [ 5, 12, 19, 26, 33],
       [ 6, 13, 20, 27, 34]])

### Flatten/Ravel

Return a contiguous flattened array.

 * raven:
     * Return only reference/view of original array.
     * Ravel is faster than flatten() as it does not occupy any memory.

 * flatten:
     * Return a copy of original array.


In [321]:
np.ravel(incr_7x5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [322]:
incr_7x5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

## Functional programming

### Apply Along Axis

Apply a function to 1-D slices along the given axis.


In [323]:
def avg_first_last(value):
    return (value[0] + value[-1]) * 0.5

Adds average to first and last element of each column

In [324]:
np.apply_along_axis(avg_first_last, 0, incr_7x5)

array([14., 15., 16., 17., 18., 19., 20.])

Adds average to first and last element of each row

In [325]:
np.apply_along_axis(avg_first_last, 1, incr_7x5)

array([ 3., 10., 17., 24., 31.])

### Custom ufunction


In [326]:
def fancy_mod3(a, b):
    return (a % 3) + (b % 3)

ufancy_mod3 = np.frompyfunc(fancy_mod3, 2, 1)

ufancy_mod3(incr_7x5, five_arr)

array([[2, 3, 4, 2, 3, 4, 2],
       [3, 4, 2, 3, 4, 2, 3],
       [4, 2, 3, 4, 2, 3, 4],
       [2, 3, 4, 2, 3, 4, 2],
       [3, 4, 2, 3, 4, 2, 3]], dtype=object)